### PR TITLE
saving output file

### PR DESCRIPTION
**Pull request by annescharf**
Hi @jmsigner and @marcosci, this app was not providing a "output.rds" file. `return() ` only seems to work properly if no calculations are done within it. I think I fixed it, but please do check in case I messed up your code. Thanks"!

### CODE REVIEW

**Comment by annescharf** [comment]
ah, and if you can find a way of showing in which units speed and distance are measured it would be awesome. As numbers without units are sometimes difficult to guess and interpret correctly. I'm not sure it is always "m" and "m/s", ctmm sometimes adjusts the units to the dataset. Not sure how it is in the `outlie()`

**Comment by annescharf** [comment]
currently working on a project, to remove the outliers by speed, I need to use a `while` loop with the max speed to include, to remove all of them. Often just removing the high speed segments once does not do the job, as new segments arise, some of them with to high speeds. Did you account for that in this function?

**Comment by annescharf** [comment]
As I also needed to know for sure I asked Chris, and all functions in ctmm always have SI units as an output, it is just in the plots were they might change. So adding to the legend "speed (m/s)" and "distance (m)" should do the job. And regarding the while loop, I do it like this and it works nicely:

```r
  outl <- outlie(srk_tl, plot=F)
  while(max(outl$speed)>25){
    srk_tl <- srk_tl[-which(outl$speed>25),]
    outl <- outlie(srk_tl, plot=F)
  }
```

**Comment by jmsigner** [comment]
@annescharf  thanks for double-checking and sharing regarding the units. Would you mind sharing how you did this with the `while`-loop? Currently we do not account for this.

**Review by jmsigner — APPROVED** [review]

**Comment by jmsigner** [comment]
Hi @annescharf , with commit 9788572 the recursive filtering for speed is now implemented.

**Pull request merged**
